/**
 * Cloudflare Access JWT Verification Module
 * Validates JWTs issued by Cloudflare Access (SSO) using edge-native Web Crypto APIs.
 * 
 * Do not edit this file.
 */

// Interface representing the environment variables
export interface Env {
	IS_LOCAL_DEV?: string;
	CF_ACCESS_TEAM_NAME?: string;
	CF_ACCESS_AUDIENCE?: string;
	ASSETS?: any;
}

// Map to cache imported CryptoKeys in memory, indexed by Key ID (kid)
const keyCache = new Map<string, CryptoKey>();

/**
 * Converts a base64url encoded string into a Uint8Array of bytes.
 * @param str The base64url encoded string.
 * @returns The decoded Uint8Array.
 */
function base64urlToBytes(str: string): Uint8Array {
	let base64 = str.replace(/-/g, '+').replace(/_/g, '/');
	while (base64.length % 4) {
		base64 += '=';
	}
	const binary = atob(base64);
	const bytes = new Uint8Array(binary.length);
	for (let i = 0; i < binary.length; i++) {
		bytes[i] = binary.charCodeAt(i);
	}
	return bytes;
}

/**
 * Converts a base64url encoded string into a UTF-8 string.
 * @param str The base64url encoded string.
 * @returns The decoded UTF-8 string.
 */
function base64urlToString(str: string): string {
	const bytes = base64urlToBytes(str);
	return new TextDecoder().decode(bytes);
}

/**
 * Fetches the JWKS keys from Cloudflare Access certs endpoint and populates the cache.
 * @param teamName The Cloudflare Access team name.
 */
async function fetchAndCacheKeys(teamName: string): Promise<void> {
	const certsUrl = `https://${teamName}.cloudflareaccess.com/cdn-cgi/access/certs`;
	const response = await fetch(certsUrl);
	if (!response.ok) {
		throw new Error(`Failed to retrieve certificates from Cloudflare Access endpoint: ${response.statusText}`);
	}

	const jwks = (await response.json()) as { keys: Array<{ kid: string; kty: string;[key: string]: any }> };
	if (!jwks || !Array.isArray(jwks.keys)) {
		throw new Error('Invalid JWKS structure returned from Cloudflare Access');
	}

	for (const keyInfo of jwks.keys) {
		if (keyInfo.kid && keyInfo.kty === 'RSA') {
			try {
				const cryptoKey = await crypto.subtle.importKey(
					'jwk',
					keyInfo,
					{
						name: 'RSASSA-PKCS1-v1_5',
						hash: { name: 'SHA-256' },
					},
					false,
					['verify']
				);
				keyCache.set(keyInfo.kid, cryptoKey);
			} catch (err) {
				// Suppress individual key import errors to process other keys
			}
		}
	}
}

/**
 * Result of the JWT verification process.
 */
export interface VerificationResult {
	isValid: boolean;
	payload?: {
		email?: string;
		[key: string]: any;
	};
	error?: string;
}

/**
 * Verifies the Cloudflare Access JWT.
 * @param jwt The JWT assertion string.
 * @param env The environment variables.
 * @returns VerificationResult indicating status, payload (if valid), or error details.
 */
export async function verifyJwt(jwt: string | null, env: Env): Promise<VerificationResult> {
	// If Cloudflare Access team name or audience is not configured, bypass validation
	if (!env.CF_ACCESS_TEAM_NAME || !env.CF_ACCESS_AUDIENCE) {
		return {
			isValid: true,
			payload: {
				email: 'local-user@openmarkdown.local',
				name: 'Local User',
			},
		};
	}

	// 1. Check local dev bypass
	if (env.IS_LOCAL_DEV === 'true') {
		return {
			isValid: true,
			payload: {
				email: 'local-dev-user@openmarkdown.local',
				name: 'Local Dev User',
			},
		};
	}

	// 2. Validate token presence
	if (!jwt) {
		return {
			isValid: false,
			error: 'Authorisation token is missing',
		};
	}

	try {
		// 3. Split JWT parts
		const parts = jwt.split('.');
		if (parts.length !== 3) {
			return {
				isValid: false,
				error: 'Authorisation token is malformed',
			};
		}

		// 4. Parse Header and Payload
		const header = JSON.parse(base64urlToString(parts[0]));
		const payload = JSON.parse(base64urlToString(parts[1]));

		// Validate token algorithm is supported
		if (header.alg !== 'RS256') {
			return {
				isValid: false,
				error: `Unsupported signing algorithm: ${header.alg}`,
			};
		}

		// Retrieve key ID
		const kid = header.kid;
		if (!kid) {
			return {
				isValid: false,
				error: 'Key ID missing in token header',
			};
		}

		// 5. Retrieve Access details from environment
		const teamName = env.CF_ACCESS_TEAM_NAME;
		const audience = env.CF_ACCESS_AUDIENCE;

		if (!teamName || !audience) {
			return {
				isValid: false,
				error: 'Cloudflare Access environment configurations are missing',
			};
		}

		// 6. Retrieve verification key from cache or fetch from JWKS
		let cryptoKey = keyCache.get(kid);
		if (!cryptoKey) {
			await fetchAndCacheKeys(teamName);
			cryptoKey = keyCache.get(kid);
		}

		if (!cryptoKey) {
			return {
				isValid: false,
				error: 'Matching verification certificate key not found',
			};
		}

		// 7. Verify cryptographic signature
		const data = new TextEncoder().encode(`${parts[0]}.${parts[1]}`);
		const signature = base64urlToBytes(parts[2]);
		const isSignatureValid = await crypto.subtle.verify(
			'RSASSA-PKCS1-v1_5',
			cryptoKey,
			signature,
			data
		);

		if (!isSignatureValid) {
			return {
				isValid: false,
				error: 'Cryptographic signature verification failed',
			};
		}

		// 8. Validate payload claims
		const now = Math.floor(Date.now() / 1000);

		// Expiration time check
		if (payload.exp && now >= payload.exp) {
			return {
				isValid: false,
				error: 'Authorisation token has expired',
			};
		}

		// Not before check
		if (payload.nbf && now < payload.nbf) {
			return {
				isValid: false,
				error: 'Authorisation token is not yet active',
			};
		}

		// Issuer check
		const expectedIssuer = `https://${teamName}.cloudflareaccess.com`;
		if (payload.iss !== expectedIssuer) {
			return {
				isValid: false,
				error: `Issuer mismatch: expected ${expectedIssuer}`,
			};
		}

		// Audience check
		// Cloudflare Access JWTs encode aud as an array (e.g. ["abc..."]), not a string
		const audValid = Array.isArray(payload.aud)
			? payload.aud.includes(audience)
			: payload.aud === audience;
		if (!audValid) {
			return {
				isValid: false,
				error: 'Audience mismatch: token was not issued for this application',
			};
		}

		return {
			isValid: true,
			payload: {
				email: payload.email,
				name: payload.common_name || payload.name,
			},
		};
	} catch (err: any) {
		return {
			isValid: false,
			error: `Token validation error: ${err.message}`,
		};
	}
}
